// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Kafka_util_instanceof = require("./Kafka_util_instanceof.bs.js");

var Client = /* module */[];

var ProduceRequest = /* module */[];

var Producer = /* module */[/* ProduceRequest */ProduceRequest];

var Payload = /* module */[];

var MakeOptions = /* module */[];

function bufferValue(message) {
  return Kafka_util_instanceof.bufferGetExn(message.value);
}

var Consumer = /* module */[
  /* Payload */Payload,
  /* MakeOptions */MakeOptions,
  /* bufferValue */bufferValue
];

exports.Client = Client;
exports.Producer = Producer;
exports.Consumer = Consumer;
/* Kafka_util_instanceof Not a pure module */
