// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var DynamicCastError = Caml_exceptions.create("Kafka_util_instanceof.DynamicCastError");


function myinstanceof(c, x) { return x instanceof c }

;

function $$instanceof(c, x) {
  return myinstanceof(c, x);
}

var bufferConstructor = (Buffer);

function instanceofBuffer(x) {
  return $$instanceof(bufferConstructor, x);
}

function maybeBuffer(x) {
  var match = instanceofBuffer(x);
  if (match) {
    return /* Some */[x];
  } else {
    return /* None */0;
  }
}

function bufferGetExn(x) {
  var match = instanceofBuffer(x);
  if (match) {
    return x;
  } else {
    throw DynamicCastError;
  }
}

exports.$$instanceof = $$instanceof;
exports.instanceofBuffer = instanceofBuffer;
exports.maybeBuffer = maybeBuffer;
exports.bufferGetExn = bufferGetExn;
/*  Not a pure module */
